INSERT INTO analytics.kobe_shots (
    shot_id,
    action_type,
    combined_shot_type,
    game_event_id,
    game_id,
    lat,
    loc_x,
    loc_y,
    lon,
    minutes_remaining,
    period,
    playoffs,
    season,
    seconds_remaining,
    shot_distance,
    shot_made_flag,
    shot_type,
    shot_zone_area,
    shot_zone_basic,
    shot_zone_range,
    team_id,
    team_name,
    game_date,
    matchup,
    opponent,
    source_name
)
VALUES (
    %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
    %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s
)
ON CONFLICT (shot_id)
DO UPDATE SET
    action_type = EXCLUDED.action_type,
    combined_shot_type = EXCLUDED.combined_shot_type,
    game_event_id = EXCLUDED.game_event_id,
    game_id = EXCLUDED.game_id,
    lat = EXCLUDED.lat,
    loc_x = EXCLUDED.loc_x,
    loc_y = EXCLUDED.loc_y,
    lon = EXCLUDED.lon,
    minutes_remaining = EXCLUDED.minutes_remaining,
    period = EXCLUDED.period,
    playoffs = EXCLUDED.playoffs,
    season = EXCLUDED.season,
    seconds_remaining = EXCLUDED.seconds_remaining,
    shot_distance = EXCLUDED.shot_distance,
    shot_made_flag = EXCLUDED.shot_made_flag,
    shot_type = EXCLUDED.shot_type,
    shot_zone_area = EXCLUDED.shot_zone_area,
    shot_zone_basic = EXCLUDED.shot_zone_basic,
    shot_zone_range = EXCLUDED.shot_zone_range,
    team_id = EXCLUDED.team_id,
    team_name = EXCLUDED.team_name,
    game_date = EXCLUDED.game_date,
    matchup = EXCLUDED.matchup,
    opponent = EXCLUDED.opponent,
    source_name = EXCLUDED.source_name,
    updated_at = CURRENT_TIMESTAMP;
